development: &defaults
  adapter: mysql2
  encoding: utf8
  database: git_development
  username: root
  password: root
  pool: 10
  reconnect: true

test:
  <<: *defaults
  database: git_test

production:
  <<: *defaults
  database: git_production
